name: regenerate

on:
  push:

jobs:
  regenerate_dist-index_js:
    runs-on: ubuntu-latest
    steps:
    - 
      uses: actions/checkout@v4.1.1
    - 
      name: regenerate dist/index.js
      run: |
        sudo npm i -g @vercel/ncc@0.26.2
        npm install
        ncc build index.js
    -
      name: Git Auto Commit
      uses: stefanzweifel/git-auto-commit-action@8756aa072ef5b4a080af5dc8fef36c5d586e521d
      with:
        file_pattern: dist/index.js
        commit_message: Regenerate dist/index.js
        
        
