name: tests

on:
  push:
    branches: [ main, master ]

  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
  
    steps:
      - name: Check out source code...
        uses: actions/checkout@v4.1.5

      - name: Running first test...
        uses: ./
        with:
          macos: echo "Hi from macos"
          linux: |
            echo "Hi from linux"
            echo "Hi from linux second line"
          windows: echo "Hi from windows"

      - name: Running second test...
        uses: ./
        with:
          macos: echo "test2"
          linux: echo "test2"
          windows: echo "test2"
          windowsShell: cmd

      - name: Running third test...
        uses: ./
        with:
          working_directory: my_new_dir/dir_2/dir3/here_5
          macos: echo "test2"
          linux: echo "test2"
          windows: echo "test2"
          windowsShell: cmd
